version: "3.8"

services:
    test_db:
        image: postgres:15.3
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
    redis:
        image: redis:latest
        restart: always
        ports:
            - "6379:6379"

    rabbitmq:
        container_name: rabbitmq_container
        image: rabbitmq:3.10.7-management
        restart: always
        ports:
            - "5672:5672"
            - "15672:15672"
        environment:
            - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
            - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
            - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
  
    # celery_worker:
    #     build:
    #         context: .
    #         dockerfile: Dockerfile
    #     command: celery -A tasks.celery_app worker -l debug
    #     depends_on:
    #         - redis
    #         - rabbitmq
    #     volumes:
    #         - shared_vol:/app
    #         - /var/run/docker.sock:/var/run/docker.sock

    # flower:
    #     build:
    #         context: .
    #         dockerfile: Dockerfile
    #     command: celery -A tasks.celery_app.celery_app flower --broker=amqp://rabbitmq:rabbitmq@rabbitmq:5672// --port=5555
    #     ports:
    #         - "5555:5555"
    #     depends_on:
    #         - rabbitmq
    #         - redis
volumes:
    shared_vol:
