FROM python:3.12.1-slim

RUN pip install --no-cache-dir --upgrade pip uv


WORKDIR /app

COPY pyproject.toml poetry.lock* ./

RUN uv pip install --from-lock-file poetry.lock && \
    uv pip install -e . && \
    rm -rf /root/.cache/uv

COPY . .

CMD ["tail", "-f", "/dev/null"]