name: ${PROJECT_NAME}_tests


services:
    backend_test:
        container_name: backend_test
        build: 
            context: .. 
            dockerfile: .devcontainer/Dockerfile
        command: bash -c "poetry run alembic upgrade head && poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
        volumes:
            - ..:/app
        ports:
            - 8000:8000
        restart: always
        depends_on:
            - test_db
        environment:
            - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
            - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    test_db:
        container_name: test_db
        image: postgres:15.3
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=${TEST_POSTGRES_USER}
            - POSTGRES_PASSWORD=${TEST_POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_TEST_DB}

    redis:
        container_name: redis_test
        image: redis:latest
        restart: always
        ports:
            - "6379:6379"

    rabbitmq:
        container_name: rabbitmq_test
        image: rabbitmq:3.10.7-management
        restart: always
        ports:
            - "5672:5672"
            - "15672:15672"
        environment:
            - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
            - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
            - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648

    celery_worker:
        container_name: celery_worker_test
        build:
            context: ..
            dockerfile: .devcontainer/Dockerfile.celery
        command: celery -A app.tasks.celery_app worker -l debug
        depends_on:
            - redis
            - rabbitmq
        volumes:
            - ../app/tasks:/app/app/tasks
            - /var/run/docker.sock:/var/run/docker.sock
            - shared_vol:/app
        environment:
            - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
            - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
            - PROJECT_NAME=${PROJECT_NAME}


    backend_tests:
        container_name: backend_tests
        build:
            context: .. 
            dockerfile: .devcontainer/Dockerfile.test
        command: bash -c "sleep 3 && poetry run pytest ./tests"
        volumes:
            - ..:/app
        depends_on:
            - backend_test

volumes:
    shared_vol:
