"""added is_published field to topic, lesson, step models

Revision ID: 3890b103305c
Revises: 7c902399eac3
Create Date: 2024-02-01 12:56:34.490038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3890b103305c'
down_revision: Union[str, None] = '7c902399eac3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson', sa.Column('is_published', sa.Boolean(), nullable=False))
    op.add_column('step', sa.Column('is_published', sa.Boolean(), nullable=False))
    op.add_column('topic', sa.Column('is_published', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topic', 'is_published')
    op.drop_column('step', 'is_published')
    op.drop_column('lesson', 'is_published')
    # ### end Alembic commands ###
