"""added user progression table

Revision ID: 61f696144ccc
Revises: 97c68726993b
Create Date: 2024-03-28 17:16:40.965065

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "61f696144ccc"
down_revision: Union[str, None] = "97c68726993b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "userprogress",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("step_id", sa.Integer(), nullable=False),
        sa.Column("is_completed", sa.Boolean(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["course.id"],
        ),
        sa.ForeignKeyConstraint(
            ["step_id"],
            ["step.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_userprogress_course_id"), "userprogress", ["course_id"], unique=False
    )
    op.create_index(
        op.f("ix_userprogress_step_id"), "userprogress", ["step_id"], unique=False
    )
    op.add_column("step", sa.Column("theory_id", sa.Integer(), nullable=True))
    op.add_column("step", sa.Column("coding_task_id", sa.Integer(), nullable=True))
    op.add_column("step", sa.Column("test_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "step", "test", ["test_id"], ["id"])
    op.create_foreign_key(None, "step", "codingtask", ["coding_task_id"], ["id"])
    op.create_foreign_key(None, "step", "theory", ["theory_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "step", type_="foreignkey")
    op.drop_constraint(None, "step", type_="foreignkey")
    op.drop_constraint(None, "step", type_="foreignkey")
    op.drop_column("step", "test_id")
    op.drop_column("step", "coding_task_id")
    op.drop_column("step", "theory_id")
    op.drop_index(op.f("ix_userprogress_step_id"), table_name="userprogress")
    op.drop_index(op.f("ix_userprogress_course_id"), table_name="userprogress")
    op.drop_table("userprogress")
    # ### end Alembic commands ###
