"""Initial migration

Revision ID: 6758d219d52e
Revises: 
Create Date: 2023-12-22 20:15:51.430141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "6758d219d52e"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pointssystem",
        sa.Column("points_id", sa.Integer(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("points_value", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("points_id"),
    )
    op.create_table(
        "user",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("password_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_author", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "course",
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "programming_language", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["user.user_id"],
        ),
        sa.PrimaryKeyConstraint("course_id"),
    )
    op.create_table(
        "favorite",
        sa.Column("favorite_id", sa.Integer(), nullable=False),
        sa.Column("student_id", sa.Integer(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["course.course_id"],
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["user.user_id"],
        ),
        sa.PrimaryKeyConstraint("favorite_id"),
    )
    op.create_table(
        "studentcourse",
        sa.Column("student_course_id", sa.Integer(), nullable=False),
        sa.Column("student_id", sa.Integer(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("points_accumulated", sa.Integer(), nullable=False),
        sa.Column("is_completed", sa.Boolean(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["course.course_id"],
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["user.user_id"],
        ),
        sa.PrimaryKeyConstraint("student_course_id"),
    )
    op.create_table(
        "topic",
        sa.Column("topic_id", sa.Integer(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["course.course_id"],
        ),
        sa.PrimaryKeyConstraint("topic_id"),
    )
    op.create_table(
        "lesson",
        sa.Column("lesson_id", sa.Integer(), nullable=False),
        sa.Column("topic_id", sa.Integer(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["topic_id"],
            ["topic.topic_id"],
        ),
        sa.PrimaryKeyConstraint("lesson_id"),
    )
    op.create_table(
        "step",
        sa.Column("step_id", sa.Integer(), nullable=False),
        sa.Column("lesson_id", sa.Integer(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column(
            "step_kind",
            sa.Enum("THEORY", "CODING_TASK", "TEST", name="stepkind"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["lesson_id"],
            ["lesson.lesson_id"],
        ),
        sa.PrimaryKeyConstraint("step_id"),
    )
    op.create_table(
        "codingtask",
        sa.Column("coding_task_id", sa.Integer(), nullable=False),
        sa.Column("step_id", sa.Integer(), nullable=False),
        sa.Column("instructions", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("starter_code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("solution_code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "simple_test_expected_output",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
        ),
        sa.Column(
            "advanced_test_code", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "test_type", sa.Enum("SIMPLE", "ADVANCED", name="testtype"), nullable=False
        ),
        sa.Column("points", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["step_id"],
            ["step.step_id"],
        ),
        sa.PrimaryKeyConstraint("coding_task_id"),
    )
    op.create_table(
        "submission",
        sa.Column("submission_id", sa.Integer(), nullable=False),
        sa.Column("student_id", sa.Integer(), nullable=False),
        sa.Column("step_id", sa.Integer(), nullable=False),
        sa.Column(
            "submitted_answer", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("is_correct", sa.Boolean(), nullable=False),
        sa.Column("points_awarded", sa.Integer(), nullable=False),
        sa.Column("submitted_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["step_id"],
            ["step.step_id"],
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["user.user_id"],
        ),
        sa.PrimaryKeyConstraint("submission_id"),
    )
    op.create_table(
        "test",
        sa.Column("test_id", sa.Integer(), nullable=False),
        sa.Column("step_id", sa.Integer(), nullable=False),
        sa.Column("question", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("points", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["step_id"],
            ["step.step_id"],
        ),
        sa.PrimaryKeyConstraint("test_id"),
    )
    op.create_table(
        "theory",
        sa.Column("theory_id", sa.Integer(), nullable=False),
        sa.Column("step_id", sa.Integer(), nullable=False),
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["step_id"],
            ["step.step_id"],
        ),
        sa.PrimaryKeyConstraint("theory_id"),
    )
    op.create_table(
        "testchoice",
        sa.Column("test_choice_id", sa.Integer(), nullable=False),
        sa.Column("test_id", sa.Integer(), nullable=False),
        sa.Column("choice_text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_correct", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["test_id"],
            ["test.test_id"],
        ),
        sa.PrimaryKeyConstraint("test_choice_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("testchoice")
    op.drop_table("theory")
    op.drop_table("test")
    op.drop_table("submission")
    op.drop_table("codingtask")
    op.drop_table("step")
    op.drop_table("lesson")
    op.drop_table("topic")
    op.drop_table("studentcourse")
    op.drop_table("favorite")
    op.drop_table("course")
    op.drop_table("user")
    op.drop_table("pointssystem")
    # ### end Alembic commands ###
