"""added author_id field to step model

Revision ID: cc0770918a03
Revises: 3890b103305c
Create Date: 2024-02-01 15:22:45.224876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "cc0770918a03"
down_revision: Union[str, None] = "3890b103305c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "step", sa.Column("author_id", sqlmodel.sql.sqltypes.GUID(), nullable=False)
    )
    op.create_foreign_key(None, "step", "user", ["author_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "step", type_="foreignkey")
    op.drop_column("step", "author_id")
    # ### end Alembic commands ###
